version: "3"
services:

    httpAPI:
        build: ./httpapi
        image: httpapi
        ports:
            - "5000:5000"
        networks:
            - backend
        depends_on:
            - cbdb
        restart: always
 
    cbdb:
        image: couchbase/server:latest
        ports:
            - "8091-8094:8091-8094"
        networks:
            - backend
        restart: always
networks:
    backend:

